# Generated by Django 4.0.3 on 2022-06-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_file', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('article_types', models.CharField(max_length=20)),
                ('article_tags', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile_file', models.CharField(max_length=40)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='token_authentication.userauthentication')),
            ],
        ),
        migrations.CreateModel(
            name='StuntReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.TimeField()),
                ('repeat_each', models.TextField(max_length=50)),
                ('on', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StuntingTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.userprofile')),
            ],
        ),
    ]
