# Generated by Django 4.0.3 on 2022-05-31 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile_file', models.CharField(max_length=40)),
                ('authentication', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='token_authentication.userauthentication')),
            ],
        ),
        migrations.CreateModel(
            name='StuntingTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.userprofile')),
            ],
        ),
    ]
