# Generated by Django 4.0.3 on 2022-05-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuntReminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.TimeField()),
                ('repeat_each', models.TextField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.userprofile')),
            ],
        ),
    ]
