# Generated by Django 4.0.3 on 2022-05-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_stuntreminders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StuntReminders',
            new_name='StuntReminder',
        ),
    ]
