# Generated by Django 4.0.3 on 2022-06-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_alter_userprofile_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
