# Generated by Django 4.0.3 on 2022-06-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0002_alter_userauthentication_role'),
        ('apiv1', '0003_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuntPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('place_name', models.CharField(max_length=50)),
                ('gmap_place_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='authentication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='token_authentication.userauthentication'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, default='   ', max_length=30, null=True),
        ),
    ]
