# Generated by Django 4.0.3 on 2022-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_rename_stuntreminders_stuntreminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuntingtrace',
            old_name='month',
            new_name='week',
        ),
        migrations.AddField(
            model_name='stuntingtrace',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuntingtrace',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
