# Generated by Django 4.0.3 on 2022-06-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_rename_month_stuntingtrace_week_stuntingtrace_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuntreminder',
            name='on',
            field=models.BooleanField(default=True),
        ),
    ]
