# Generated by Django 4.0.3 on 2022-06-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuntingtrace',
            name='age_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stuntingtrace',
            name='disease_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stuntingtrace',
            name='exclusive_asi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stuntingtrace',
            name='immunization_history',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
