# Generated by Django 4.0.3 on 2022-06-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_stuntreminder_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_file', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('article_types', models.CharField(max_length=20)),
                ('article_tags', models.CharField(max_length=60)),
            ],
        ),
    ]
