# Generated by Django 4.0.3 on 2022-06-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_stuntingtrace_age_day_stuntingtrace_disease_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuntplace',
            name='img_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
