# Generated by Django 4.0.3 on 2022-06-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_stuntplace_img_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuntplace',
            name='img_name',
        ),
        migrations.AddField(
            model_name='stuntplace',
            name='img_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
