# Generated by Django 4.0.3 on 2022-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_remove_stuntplace_img_name_stuntplace_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_cover_file',
            field=models.CharField(default='', max_length=50),
        ),
    ]
