# Generated by Django 4.0.3 on 2022-06-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0009_article_article_cover_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_types',
            new_name='article_type',
        ),
        migrations.AddField(
            model_name='article',
            name='article_sub_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
