# Generated by Django 4.0.3 on 2022-07-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0011_alter_article_article_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuntplace',
            name='avg_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuntplace',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stuntplace',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.CreateModel(
            name='StuntPlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('stunt_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.stuntplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HealthWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=25)),
                ('desc', models.CharField(default='', max_length=150)),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.stuntplace')),
            ],
        ),
    ]
