# Generated by Django 4.0.3 on 2022-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0013_reporter_article1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('js', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article1',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
