# Generated by Django 4.0.3 on 2022-07-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0014_test_delete_article1_delete_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='js',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
