# Generated by Django 4.0.3 on 2022-07-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0015_alter_test_js'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
