# Generated by Django 4.0.3 on 2022-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0018_generalconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funstuntqa',
            old_name='content_file',
            new_name='question_file',
        ),
        migrations.AddField(
            model_name='funstuntqa',
            name='answers_file',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
