# Generated by Django 4.0.3 on 2022-08-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0019_rename_content_file_funstuntqa_question_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funstuntqa',
            name='correct_answer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
