# Generated by Django 4.0.3 on 2022-08-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0020_funstuntqa_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuntplace',
            name='avg_rating',
            field=models.FloatField(),
        ),
    ]
