# Generated by Django 4.0.3 on 2022-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0023_children_parent_stuntingtrace_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
