# Generated by Django 4.0.3 on 2022-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0024_children_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
