# Generated by Django 4.0.3 on 2022-08-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0025_children_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stuntingtrace',
            unique_together={('user', 'week', 'children')},
        ),
    ]
