# Generated by Django 4.0.3 on 2022-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0026_alter_stuntingtrace_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuntingtrace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-08-04 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuntingtrace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
