# Generated by Django 4.0.3 on 2022-08-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0028_stuntingtrace_is_stunting_stuntingtrace_z_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuntingtrace',
            old_name='is_stunting',
            new_name='growth_level',
        ),
    ]
