# Generated by Django 4.0.3 on 2022-06-01 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='token_authentication.userrole'),
        ),
    ]
