name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: gcp_minimum
    steps:
    - uses: actions/checkout@v1

    # - name: Executing remote command
    #   uses: appleboy/ssh-action@master
    #   env:
    #     HOST: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PORT: 22
    #     PASSWORD: ${{ secrets.PASSWORD }}
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     port: 22
    #     password: ${{ secrets.PASSWORD }}
    #     script: git pull origin main


    - name: Run a multi-line script
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo 'hello' $HOST $USERNAME  $PASSWORD
        sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$HOST 'cd /home/kevinagusto28/Stunting-Health-PKM && git pull origin main'
        

    # - name: Copy repository contents via scp
    #   uses: appleboy/scp-action@master
    #   env:
    #     HOST: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PORT: ${{ secrets.PORT }}
    #     PASSWORD: ${{ secrets.PASSWORD }}
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     port: 22
    #     password: ${{ secrets.PASSWORD }}
    #     source: "deploy.tar"
    #     target: "/home/kevinagusto28/stunt/"

