name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: gcp_minimum
    steps:
    - uses: actions/checkout@v1

    - name: SSH Using Appleboy
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        PASSWORD: ${{ secrets.PASSWORD }}
      with:
        envs: HOST, USERNAME, PASSWORD
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        password: ${{ secrets.PASSWORD }}
        script: |
        cd "/home/${USERNAME}/Stunting-Health-PKM" && git pull origin main
        sshpass -p "${PASSWORD}" ssh -o StrictHostKeyChecking=no "$USERNAME@$HOST" "cd /home/${USERNAME}/Stunting-Health-PKM && python3 -m pip install -r requirements.txt &&python3 manage.py runserver ${HOST}:8000"
        

    - name: SSH using script
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        sshpass -p "${PASSWORD}" ssh -o StrictHostKeyChecking=no "$USERNAME@$HOST" "cd /home/${USERNAME}/Stunting-Health-PKM && git pull origin main"
        
