name: Deploy

on: [push]
# inputs:
#   debug:
#     description: 'enable debug mode'
#     default: false
jobs:
  build:

    runs-on: ubuntu-latest
    environment: gcp_minimum
    steps:
    - uses: actions/checkout@v1

    # - name: Copy repository contents via scp
    #   uses: appleboy/scp-action@master
    #   env:
    #     HOST: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PORT: 22
    #     KEY: ${{ secrets.PASSWORD }}
    #   with:
    #     source: "."
    #     target: "/var/www/mywebsite"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      

      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        PASSWORD: ${{ secrets.PASSWORD }}
      # run: echo $USERNAME
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        password: ${{ secrets.PASSWORD }}
        script:  echo $HOST #&& apt-get update -qq && apt-get install -y -qq sshpass #&& sshpass -p $KEY ssh -o StrictHostKeyChecking=no $USERNAME@$HOST 'touch /home/kevinagusto28/test'